#server:
#  port: 9000

spring:
#  mvc:
#    static-path-pattern: /statics/** #静态文件配置
  application:
    name: robot-keeper
  redis:
    database: 0 #索引（默认为0）
    host: 127.0.0.1 #地址
    port: 6379 #端口号
    #password:  #连接密码（默认空）
    timeout: 6000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mc_oauth?useUnicode=true&characterEncoding=utf-8&connectTimeout=60000&socketTimeout=60000&serverTimezone=GMT%2B8
    username: root
    password: hy190418
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8

package:
  pkg-path: com.robot.test
  service-is-interface: true
  name-strategy:
    scheme: UNDERLINE_TO_CAMEL
    class-remove-prefix:
      - "mc_"

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web: INFO
    tk.mybatis.pagehelper.mapper: TRACE